### ISSUE TITLE
y marchent plus les boutons !! :P

### ISSUE THREAD

**Issue by Tifnou** [DimitriMockelyn/ASLB_WEB#1]
Dimitri,

tu as du désactiver la possibilité de cliquer sur l'historique coachs, etc.
En fait c'est juste pour tester la plateforme de remonter d'info ^^...mais c'est vrai qu'ils ne fonctionnent plus :p 

Stef

**Comment by DimitriMockelyn** [comment]
Le probleme était causé par la modification du fond du site, qui prenait le dessus sur tout (Le logo ASLB était prioritaire sur le clic sur certains éléments).
